const tasks = [
  {
    id: "1",
    title: "Implement login page",
    description: "Create a responsive login page with form validation.",
    tags: ["frontend", "auth"],
    deadline: "2025-02-12T23:59:00Z",
    status: "TO-DO",
    priority: "high",
    assignee: {
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      image: "https://i.pravatar.cc/150?u=alice.johnson",
    },
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-02-02T14:00:00Z",
    comments: [],
    attachments: [],
  },
  {
    id: "2",
    title: "Set up database schema",
    description: "Design and implement the initial database schema.",
    tags: ["backend", "database"],
    deadline: "2025-02-15T23:59:00Z",
    status: "TO-DO",
    priority: "medium",
    assignee: {
      name: "Bob Smith",
      email: "bob.smith@example.com",
      image: "https://i.pravatar.cc/150?u=bob.smith",
    },
    created_at: "2025-02-02T09:30:00Z",
    updated_at: "2025-02-03T11:00:00Z",
    comments: [],
    attachments: ["schema-diagram.pdf"],
  },
  {
    id: "3",
    title: "Fix navbar responsiveness",
    description: "Ensure the navbar adapts correctly on all screen sizes.",
    tags: ["frontend", "UI"],
    deadline: "2025-02-10T23:59:00Z",
    status: "IN-PROGRESS",
    priority: "high",
    assignee: {
      name: "Charlie Adams",
      email: "charlie.adams@example.com",
      image: "https://i.pravatar.cc/150?u=charlie.adams",
    },
    created_at: "2025-02-02T12:00:00Z",
    updated_at: "2025-02-04T09:45:00Z",
    comments: [
      {
        user: "Dave Lee",
        text: "The mobile menu still needs improvement.",
        timestamp: "2025-02-03T08:30:00Z",
      },
    ],
    attachments: [],
  },
  {
    id: "4",
    title: "Implement email notifications",
    description: "Set up email notifications for user sign-ups.",
    tags: ["backend", "notifications"],
    deadline: "2025-02-20T23:59:00Z",
    status: "IN-PROGRESS",
    priority: "medium",
    assignee: {
      name: "Eva Martinez",
      email: "eva.martinez@example.com",
      image: "https://i.pravatar.cc/150?u=eva.martinez",
    },
    created_at: "2025-02-03T15:30:00Z",
    updated_at: "2025-02-04T10:20:00Z",
    comments: [
      {
        user: "Frank Thomas",
        text: "Should we support HTML emails?",
        timestamp: "2025-02-04T07:10:00Z",
      },
    ],
    attachments: ["email-template.html"],
  },
  {
    id: "5",
    title: "Code review for authentication module",
    description:
      "Review the authentication module for security vulnerabilities.",
    tags: ["backend", "security"],
    deadline: "2025-02-18T23:59:00Z",
    status: "IN-REVIEW",
    priority: "high",
    assignee: {
      name: "Grace Cooper",
      email: "grace.cooper@example.com",
      image: "https://i.pravatar.cc/150?u=grace.cooper",
    },
    created_at: "2025-02-05T11:00:00Z",
    updated_at: "2025-02-06T14:30:00Z",
    comments: [
      {
        user: "Henry White",
        text: "Check if the password hashing algorithm meets security standards.",
        timestamp: "2025-02-06T12:15:00Z",
      },
    ],
    attachments: [],
  },
  {
    id: "6",
    title: "Design system documentation",
    description: "Document the design system components and guidelines.",
    tags: ["UI/UX", "docs"],
    deadline: "2025-02-25T23:59:00Z",
    status: "IN-REVIEW",
    priority: "medium",
    assignee: {
      name: "Ivy Nelson",
      email: "ivy.nelson@example.com",
      image: "https://i.pravatar.cc/150?u=ivy.nelson",
    },
    created_at: "2025-02-06T10:15:00Z",
    updated_at: "2025-02-07T08:50:00Z",
    comments: [],
    attachments: ["design-system-guide.pdf"],
  },
  {
    id: "9",
    title: "Implement login page",
    description: "Create a responsive login page with form validation.",
    tags: ["frontend", "auth"],
    deadline: "2025-02-12T23:59:00Z",
    status: "TO-DO",
    priority: "high",
    assignee: {
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      image: "https://i.pravatar.cc/150?u=alice.johnson",
    },
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-02-02T14:00:00Z",
    comments: [],
    attachments: [],
  },
];

export default tasks;
